name: "Run tests"

run-name: "Run tests"

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  test:
    name: "Test"
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            python_version: 
                - "2.7.17"
                - "2.7.18"
                - "3.0.1"
                - "3.1.4"
                - "3.2.5"
                - "3.3.5"
                - "3.3.7"
                - "3.4.4"
                - "3.4.10"
                - "3.5.4"
                - "3.5.10"
                - "3.6.7"
                - "3.6.15"
                - "3.7.1"
                - "3.7.16"
                - "3.8.0"
                - "3.8.16"
                - "3.9.0"
                - "3.9.16"
                - "3.10.0"
                - "3.10.11"
                - "3.11.0"
                - "3.11.3"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up Python ${{ matrix.python_version }}"
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python_version }}
      - name: "Install dependencies"
        run: |
            python -m pip install --upgrade pip
            pip install -e ./src/
      - name: "Run tests"
        run: |
            python -m unittest discover ./src/