name: "Run tests"

run-name: "Run tests"

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  test:
    name: "Test"
    # concurrency:
    #   group: "test-${{ matrix.os }}"
    strategy:
        fail-fast: false
        max-parallel: 4
        matrix:
            os: [ubuntu-20.04, windows-latest]
            # Exclude Python versions that are not supported on the OS
            exclude:
              - os: ubuntu-20.04
                python_version: "3.0.1"
              - os: ubuntu-20.04
                python_version: "3.2.5"
              - os: ubuntu-20.04
                python_version: "3.3.5"
              - os: ubuntu-20.04
                python_version: "3.3.7"
              - os: ubuntu-20.04
                python_version: "3.4.4"
              - os: ubuntu-20.04
                python_version: "3.4.10"
                
              - os: windows-latest
                python_version: "3.3.7"
              - os: windows-latest
                python_version: "3.4.10"
              - os: windows-latest
                python_version: "3.5.10"
              - os: windows-latest
                python_version: "3.6.15"
              - os: windows-latest
                python_version: "3.7.16"
              - os: windows-latest
                python_version: "3.8.16"
            python_version: 
                - "2.7.17"
                - "2.7.18"
                - "3.0.1"
                - "3.2.5"
                - "3.3.5"
                - "3.3.7"
                - "3.4.4"
                - "3.4.10"
                - "3.5.4"
                - "3.5.10"
                - "3.6.7"
                - "3.6.15"
                - "3.7.1"
                - "3.7.16"
                - "3.8.0"
                - "3.8.16"
                - "3.9.0"
                - "3.10.0"
                - "3.10.11"
                - "3.11.0"
                - "3.11.3"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install pip"
        run: |
            curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py
            python get-pip.py
            python -m pip install --upgrade "pip < 21.0"
        
      - name: "Set up Python ${{ matrix.python_version }}"
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python_version }}
        
      - name: "Run tests"
        run: |
            python -m unittest discover ./src/