name: "CPython tests (Windows)"

run-name: "Run CPython tests on Windows"

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    strategy:
      fail-fast: false
      # max-parallel: 6
      matrix:
        os: 
          - windows-latest
        python_version:
        # See issue #9 for more information
        #   - "2.7.17"
        #   - "2.7.18"
          - "3.2.5"
          - "3.3.5"
          - "3.4.4"
          - "3.5.4"
          - "3.6.7"
          - "3.7.1"
          - "3.8.0"
          - "3.9.0"
          - "3.10.0"
          - "3.10.11"
          - "3.11.0"
          - "3.11.3"
          
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        
      - name: "Set up Python ${{ matrix.python_version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          check-latest: false
        
      - name: "Run tests"
        run: |
          python ./scripts/run_tests.py --verbose --pattern "*.py"